services:
  app:
    container_name: app
    restart: always
    build:
      context: .
      target: dependencies
    command: dumb-init pnpm --parallel --filter @lambada/* run dev
    volumes:
      - .:/home/node/lambada/
      - /home/node/lambada/.pnpm-store
      - /home/node/lambada/node_modules
      - /home/node/lambada/apps/api/node_modules
      - /home/node/lambada/apps/frontend/node_modules
    ports:
      - 3333:3333
      - 3000:3000
      - 9229:9229

  db:
    container_name: db
    image: postgres:14-alpine
    restart: always
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
    ports:
     - "5432:5432"

  mail:
    container_name: mailhog
    image: mailhog/mailhog
    ports:
     - "1025:1025"
     - "8025:8025" 

volumes:
  postgres_volume:
  
    

   