services: 
  serverweb:
    image: nginx:1-alpine
    ports:
      - "8080:80"
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80


  db:
    image: postgres:14-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    ports:
     - "5432:5432"


  mail:
    image: mailhog/mailhog
    ports:
     - "1025:1025"
     - "8025:8025" 
    

   